2 модуль
js-tasks-ru/jsbasic-20210621_erlenchik07 pull request #3
Opened 2021-06-30 17:06 UTC by Erlenchik

2021-06-30 17:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-01 15:22 UTC, SinimaWath requested changes

2021-07-01 15:22 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (typeof salaries[key] === 'number' && !isNaN(salaries[key]) && isFinite(salaries[key])) {
молодец, что сама написала проверку.

В браузере еще есть Number.isFinite()

2021-07-01 15:22 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  else { return false;}
Давай упростим до одной строчки, результать операции `Object.keys(obj).length === 0` и так уже true/false

2021-07-01 16:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-02 13:53 UTC, SinimaWath requested changes

2021-07-02 13:53 UTC, SinimaWath commented on 2-module/2-task/index.js
> +}
У тебя тут падают тесты, так как нет return

2021-07-04 16:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-05 19:57 UTC, SinimaWath approved these changes

2021-07-05 19:57 UTC, merged